language: node_js
node_js:
  - "10"
cache:
  yarn: false

services:
  - docker

stages:
  - build
  - build docker image
  - name: dockerhub dev deploy
    if: (branch = master) AND (NOT (type = pull_request))
  - name: dockerhub deploy
    if: tag IS present

jobs:
  include:
    - stage: build
      script:
        - npm run eslint
        - npm run compilex64

    - stage: build docker image
      install: true
      script:
        - docker build -t dungeon-revealer -f Dockerfile .
        - docker run --rm dungeon-revealer echo "hello"

    - stage: dockerhub dev deploy
      install: true
      script:
        - echo "Deploying dev to Dockerhub..."
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/dungeon-revealer:dev .
        - docker images
        - docker push $DOCKER_USERNAME/dungeon-revealer

    - stage: dockerhub deploy
      install: true
      script:
        - echo "Deploying $TRAVIS_TAG, latest to Dockerhub..."
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/dungeon-revealer:$TRAVIS_TAG -t $DOCKER_USERNAME/dungeon-revealer:latest .
        - docker images
        - docker push $DOCKER_USERNAME/dungeon-revealer
